# Generated by Django 5.1.7 on 2025-05-19 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0003_head'),
        ('dsa', '0001_initial'),
        ('hall', '0002_initial'),
        ('user', '0005_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('bachelor', 'Bachelor'), ('masters', 'Masters')], default='bachelor', max_length=10)),
                ('is_head_approved', models.BooleanField(default=False)),
                ('is_librarian_approved', models.BooleanField(default=False)),
                ('is_dsa_approved', models.BooleanField(default=False)),
                ('is_controller_approved', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('total_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_last_exam', models.DateField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='discipline.discipline')),
                ('dsa_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='dsa.dsa')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='hall.hall')),
                ('head_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='discipline.head')),
                ('librarian_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='user.librarian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='user.student')),
            ],
            options={
                'verbose_name': 'Apply Form',
                'verbose_name_plural': 'Apply Forms',
                'db_table': 'apply_form',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='form.applyform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
