# Generated by Django 5.1.7 on 2025-05-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_head'),
        ('dsa', '0001_initial'),
        ('form', '0001_initial'),
        ('user', '0006_alter_librarian_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyform',
            name='dsa_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='dsa.dsa'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='head_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='discipline.head'),
        ),
        migrations.AlterField(
            model_name='applyform',
            name='librarian_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='user.librarian'),
        ),
    ]
