# Generated by Django 5.1.7 on 2025-05-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_alter_applyform_dsa_approved_by_and_more'),
        ('hall', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyform',
            old_name='is_controller_approved',
            new_name='is_provost_approved',
        ),
        migrations.AddField(
            model_name='applyform',
            name='provost_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_forms', to='hall.provost'),
        ),
    ]
