# Generated by Django 5.1.7 on 2025-04-29 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['discipline_code']},
        ),
        migrations.AlterModelTable(
            name='discipline',
            table='discipline',
        ),
    ]
