# Generated by Django 5.1.7 on 2025-05-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_alter_discipline_options_alter_discipline_table'),
        ('user', '0005_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='discipline.discipline')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='user.teacher')),
            ],
            options={
                'verbose_name': 'Head',
                'verbose_name_plural': 'Heads',
                'db_table': 'head',
            },
        ),
    ]
