# Generated by Django 5.1.7 on 2025-05-19 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_librarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa', to='user.teacher')),
            ],
            options={
                'verbose_name': 'DSA',
                'verbose_name_plural': 'DSAs',
                'db_table': 'dsa',
            },
        ),
    ]
