DISCIPLINES = [
    {"name": "Architecture", "discipline_code": "01"},
    {"name": "Computer Science and Engineering", "discipline_code": "02"},
    {"name": "Businesses Administration", "discipline_code": "03"},
    {"name": "Urban and Rural Planning", "discipline_code": "04"},
    {"name": "Forestry and Wood Technology", "discipline_code": "05"},
    {"name": "Fisheries and Marian Resources Technology", "discipline_code": "06"},
    {"name": "Biotechnology and Genetics Engineering", "discipline_code": "07"},
    {"name": "Agro Technology", "discipline_code": "08"},
    {"name": "Electronics and Communication Engineering", "discipline_code": "09"},
    {"name": "Environmental Science", "discipline_code": "10"},
    {"name": "Pharmacy", "discipline_code": "11"},
    {"name": "Mathematics", "discipline_code": "12"},
    {"name": "Soil Water and Environment", "discipline_code": "13"},
    {"name": "English", "discipline_code": "14"},
    {"name": "Economics", "discipline_code": "15"},
    {"name": "Sociology", "discipline_code": "16"},
    {"name": "Physics", "discipline_code": "17"},
    {"name": "Chemistry", "discipline_code": "18"},
    {"name": "Bangla", "discipline_code": "19"},
    {"name": "Statistics", "discipline_code": "20"},
    {"name": "Development Studies", "discipline_code": "21"},
    {"name": "Drawing and Printing", "discipline_code": "22"},
    {"name": "Printmaking", "discipline_code": "23"},
    {"name": "Sculpture", "discipline_code": "24"},
    {"name": "Human Resources and Management", "discipline_code": "25"},
    {"name": "Mass Communication and Journalism", "discipline_code": "26"},
    {"name": "History and Civilization", "discipline_code": "27"},
    {"name": "Law", "discipline_code": "28"},
    {"name": "Education", "discipline_code": "29"},
]