# Generated by Django 5.1.7 on 2025-05-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='librarians', to=settings.AUTH_USER_MODEL),
        ),
    ]
