# Generated by Django 5.1.7 on 2025-05-12 11:01

import django.db.models.deletion
import utils.mixins.date_range_mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provosts', to='hall.hall')),
            ],
            bases=(utils.mixins.date_range_mixins.DateRangeStatusMixin, models.Model),
        ),
    ]
