# Generated by Django 5.1.7 on 2025-05-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hall', '0001_initial'),
        ('user', '0004_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='provost',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provosts', to='user.teacher'),
        ),
    ]
